alter table NAKLEIKA_ADVERTISEMENT add constraint FK_NAKLEIKA_ADVERTISEMENT_ON_STICKER foreign key (STICKER_ID) references NAKLEIKA_STICKER(ID);
create index IDX_NAKLEIKA_ADVERTISEMENT_ON_STICKER on NAKLEIKA_ADVERTISEMENT (STICKER_ID);
