-- begin NAKLEIKA_CAR
alter table NAKLEIKA_CAR add constraint FK_NAKLEIKA_CAR_ON_COLOR foreign key (COLOR_ID) references NAKLEIKA_D_CAR_COLOR(ID)^
alter table NAKLEIKA_CAR add constraint FK_NAKLEIKA_CAR_ON_CAR_MODEL foreign key (CAR_MODEL_ID) references NAKLEIKA_D_CAR_MODEL(ID)^
alter table NAKLEIKA_CAR add constraint FK_NAKLEIKA_CAR_ON_IMAGE_FILE foreign key (IMAGE_FILE_ID) references SYS_FILE(ID)^
create unique index IDX_NAKLEIKA_CAR_UK_PLATE_NUMBER on NAKLEIKA_CAR (PLATE_NUMBER) where DELETE_TS is null ^
create index IDX_NAKLEIKA_CAR_ON_COLOR on NAKLEIKA_CAR (COLOR_ID)^
create index IDX_NAKLEIKA_CAR_ON_CAR_MODEL on NAKLEIKA_CAR (CAR_MODEL_ID)^
create index IDX_NAKLEIKA_CAR_ON_IMAGE_FILE on NAKLEIKA_CAR (IMAGE_FILE_ID)^
-- end NAKLEIKA_CAR
-- begin NAKLEIKA_ADVERTISEMENT
alter table NAKLEIKA_ADVERTISEMENT add constraint FK_NAKLEIKA_ADVERTISEMENT_ON_ADVERTISER foreign key (ADVERTISER_ID) references NAKLEIKA_ADVERTISER(ID)^
alter table NAKLEIKA_ADVERTISEMENT add constraint FK_NAKLEIKA_ADVERTISEMENT_ON_STICKER foreign key (STICKER_ID) references NAKLEIKA_STICKER(ID)^
create index IDX_NAKLEIKA_ADVERTISEMENT_ON_ADVERTISER on NAKLEIKA_ADVERTISEMENT (ADVERTISER_ID)^
create index IDX_NAKLEIKA_ADVERTISEMENT_ON_STICKER on NAKLEIKA_ADVERTISEMENT (STICKER_ID)^
-- end NAKLEIKA_ADVERTISEMENT
-- begin NAKLEIKA_DRIVER
alter table NAKLEIKA_DRIVER add constraint FK_NAKLEIKA_DRIVER_ON_CAR foreign key (CAR_ID) references NAKLEIKA_CAR(ID)^
create unique index IDX_NAKLEIKA_DRIVER_UK_PHONE_NUMBER on NAKLEIKA_DRIVER (PHONE_NUMBER) where DELETE_TS is null ^
create index IDX_NAKLEIKA_DRIVER_ON_CAR on NAKLEIKA_DRIVER (CAR_ID)^
-- end NAKLEIKA_DRIVER
-- begin NAKLEIKA_ADVERTISER
alter table NAKLEIKA_ADVERTISER add constraint FK_NAKLEIKA_ADVERTISER_ON_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID)^
create unique index IDX_NAKLEIKA_ADVERTISER_UK_PHONE_NUMBER on NAKLEIKA_ADVERTISER (PHONE_NUMBER) where DELETE_TS is null ^
create index IDX_NAKLEIKA_ADVERTISER_ON_IMAGE on NAKLEIKA_ADVERTISER (IMAGE_ID)^
-- end NAKLEIKA_ADVERTISER
-- begin NAKLEIKA_EMPLOYEE
create unique index IDX_NAKLEIKA_EMPLOYEE_UK_PHONE_NUMBER on NAKLEIKA_EMPLOYEE (PHONE_NUMBER) where DELETE_TS is null ^
-- end NAKLEIKA_EMPLOYEE
